# Schema for the configuration files of the Election Social Integration module.
localgov_elections_reporting_social_post.settings:
  type: config_object
  label: 'Election Social Integration settings'
  mapping:
    message_template:
      type: string
      label: 'Message template'
